export const BUSINESS_GROUP_WEIGHTS = {
  KEEP_SAME_COORDINATES_BUILDING_TOGETHER: 100,
  KEEP_CLEANER_SEQUENCE: 40,
  KEEP_SAME_CLEANER_TASKS_TOGETHER: 30,
  KEEP_PRIORITY_COMPATIBLE_TASKS_TOGETHER: 20,
  KEEP_NEARBY_CLUSTER_TOGETHER: 15,
} as const;

export const BUSINESS_GROUP_THRESHOLDS = {
  SAME_COORDINATES_BUILDING_TOLERANCE_METERS: 100,
  NEARBY_CLUSTER_MAX_TRAVEL_MIN: 10,
  PRIORITY_COMPATIBLE_MIN_OVERLAP_MIN: 45,
} as const;
